### ISSUE TITLE
Integrate Bus Stops and Google Places into one search endpoint

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-backend#101]
Currently, we take local BusStop objects (with a name and coordinates) and we mix backend's Google Places result with these bus stops, also applying a fuzzy search for autocomplete / typos. As we move to Android, we should consolidate all search terms into once source to keep the clients simple.

We will transition `getGooglePlaces` to `searchPlaces`, and it will return both Google Place autocomplete results and bus stops. The schema will look something like this:

```
{
    "data" : [
        "resultName" : {
            "type" : "googlePlace"
            "detail" : "123 Jack St."
            "placeID" : "abc-xyz"
        },
        "resultName" : {
            "type" : "busStop"
            "lat" : 0.0
            "long" : 0.0
        }
    ]
}
```

**Comment by kevinchan159** [comment]
@mattbarker016 just for clarification, when you say to return both autocomplete results and bus stops, are you referring to an array of all the bus stops or a specific subset?

**Comment by mattbarker016** [comment]
An array that returns a list of locations, some of which are bus stops, some of which are Google Places.

**Comment by alanna-zhou** [comment]
@mattbarker016 do you think it would make more sense to have the json like this:

```
{
    "data" : [
        {
            "name" : "resultName",
            "type" : "googlePlace",
            "detail" : "123 Jack St.",
            "placeID" : "abc-xyz"
        },
        {
            "name" : "resultName",
            "type" : "busStop",
            "lat" : 0.0,
            "long" : 0.0
        }
    ]
}
```

?
@kevinchan159

**Comment by mattbarker016** [comment]
Yeah, that works!

**Comment by kevinchan159** [comment]
Done in #166
