### ISSUE TITLE
Route sorting based on inputs

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-backend#102]
Design proposed a new way to sort bus routes. Below is a in-progress screenshot. We want to do this sorting on the backend to avoid duplicate logic.

<img width="122" alt="image" src="https://user-images.githubusercontent.com/8039928/48316510-99148b80-e5b2-11e8-81ae-6ce3d36cd1be.png">

### General

**Section 1: Boarding Soon**
All other bus routes that involve different "from" bus stops. Sorted to get people there the fastest.

**Section 2: Walking Routes**

### Edge Case: Leaving from Bus Stop
_This is only when the "from" location is a specific bus stop._

**Section 1: From [Bus Stop Name]**
Routes that _only_ leave from that specific bus stop.

**Section 2: Boarding Soon**
All other bus routes with different "from" bus stops. Sorted by fastest arrival time.

**Section 3: Walking Routes**

## Response

Data will map to a JSON object instead of an array of routes. The key of each field should be the name of the section, which client-side will read directly to access the name of the stop. The value will be an array of routes. Work with Maya on design for the proper language.

```
{
    "data" : {
       "From Ithaca Commons - Seneca St." : [
             { "route1" : ... } , ...
        ],
        "Boarding Soon" : [
             { "route2" : ... } , ...
        ],
        "Walking Routes" : [
             { "route3" : ... } , ...
        ],
    }
}
```

**Comment by young-k** [comment]
@kevinchan159 @alanna-zhou the next step is to implement the **Edge Case: Leaving from Bus Stop** section, I've already added functionality so that walking routes are always returned no matter what!

**Comment by kevinchan159** [comment]
@mattbarker016 we're going to change the format of the response to something like this since you probably don't want dynamic keys
```
{
    "data" : {
       "fromStop" : [
             { "route1" : ... } , ...
        ],
        "boardingSoon" : [
             { "route2" : ... } , ...
        ],
        "walking" : [
             { "route3" : ... } , ...
        ],
    }
}
```

**Comment by mattbarker016** [comment]
Yeah, that makes sense actually, my bad!
