### ISSUE TITLE
Don't show delayed routes if delayed by <= 2 minutes

### ISSUE THREAD

**Issue by young-k** [cuappdev/ithaca-transit-backend#217]
The live tracking only gets updated every 30 seconds and it's finicky sometimes, and people miss the bus because they expect it to be delayed but it's not.

**Comment by young-k** [comment]
was this resolved? @alanna-zhou

**Comment by alanna-zhou** [comment]
> was this resolved? @alanna-zhou

iOS is dealing with this now.
