### ISSUE TITLE
Update README to explain how to run locally better

### ISSUE THREAD

**Issue by alanna-zhou** [cuappdev/ithaca-transit-backend#259]
To run `ithaca-transit-backend` locally, you first build node (`npm run build:dev`), start up its microservices (`npm run start:microservices`), and then run node (`npm run start:node`).

However, you only really need to run `npm run build:dev` and `npm run start:microservices` once! (Unless you are building an image for production, make sure to do `npm run build:dev` right before doing that!) The reason why you don't need to do `npm run build:dev` every time is because of `volumes` in the `docker-compose.yml`, which allows for hot reloading.

And whenever you change the code and want to run node locally you will always have to run `npm run start:node`.

It is helpful to understand the `scripts` in `package.json`. What's happening is that when you run `npm run start:node`, it goes to find `start:node`'s value in `package.json`'s `scripts`. You can see that it's `docker-compose up node`. This makes sense because in `docker-compose.yml`, you can see that the `target` is `development`. And the command for starting `development` is `npm run start:dev`, which takes us back to `package.json` and its value tells us to actually execute some magic (`./node_modules/.bin/webpack…`). The reason why we do this is because `npm run start:node` lets us run on our local computers while `npm run start:dev` runs inside the image.

**Comment by esfinkel** [comment]
Completed. see #265
