### ISSUE TITLE
v2: Refactor Models

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-backend#41]
# Models

## Route
- departureTime: Date
- arrivalTime: Date
- startCoords: Coordinates // see below
- endCoords: Coordinates // see below
- travelDistance: Double // distance between start and end coords in miles
- startName: String
- endName: String
- boundingBox: Bounds // see below
- totalDuration: Int // minutes between departureTime and arrivalTime
- routeSummary: [RouteSummaryElement] // see @myo3's comment below
- detailDirections: [Direction] // see comment below

## Direction
- type: DirectionType
- name: String // General Description (bus stop name, Google Place name)
- startLocation: Location
- endLocation: Location
- startTime: Date
- endTime: Date
- path: [Coordinates]
- travelDistance: Double
- routeNumber: Int
- stops: [Location]
- stayOnBusTransfer: Bool
- tripIdentifiers: [String]?
- delay: Int?

### detailDirections Logic
*see Route.swift Line 164 on for front-end implantation*

1. You will need to create `arrive` and `.transfer` directions. Use `DirectionType` accordingly and *correctly*. `stayOnBusTransfer` will help with the latter.
2. Remove the first and last stop in each direction with stops if stops isn't empty.
3. Make sure the last direction's name is the ending location.

A typical route should be
```
[.walk, .depart, .arrive, .walk]
```

A route with two buses should be
```
[.walk, .depart, .arrive, .depart, .arrive, .walk]
```
There is no walking at `index 3` because the user waits at the bus stop.

A route with a stay on bus transfer should be
```
[.walk, .depart, .transfer, .arrive, .walk]
```

# Other Relevant Classes

**Bounds** 
```
"bounds" :  {
    "minLat" : Double,
    "minLong" : Double,
    "maxLat" : Double,
    "maxLong" : Double
}
```

**Coordinates**
```
"coordinates" : {
    "lat" : Double,
    "long" : Double
}
```

**DirectionType**
```
enum DirectionType: String {
    case walk // Directions that involving walking
    case depart // Directions where the user gets on the bus
    case arrive // Direction where the user gets off the bus
    case transfer // IMPORTANT: Direction where transfer is involved, but user stays on bus
}
```

**Location** 
```
"location" :  {
    "name" : String,
    "id" : String, // Identifier associated with location, used mainly for stopID for bus stop locations
    "lat" : Double,
    "long" : Double
}
```

**Comment by myo3** [comment]
# Route Summary
**Note:** `routeSummary: [RouteSummaryElement]` should not include the first walking direction
- That is, the first element in routeSummary should be the first `.bus` `RouteSummaryElement`.
- _Exception:_ If walk only route, then the first element in `routeSummary` will be `.walk` `RouteSummaryElement`
## Route Summary Element
```
class RouteSummaryElement {
   var stopName: String
   var direction: RouteSummaryDirection?
   var shouldStayOnBus: Bool
}
```

### RouteSummaryDirection
```
enum RouteSummaryDirection {
    case walk
    case bus(Int) // where Int is bus number
}
```

## Examples

### Bus Stop Only Route
<img width="476" alt="screen shot 2018-08-30 at 12 40 21 pm" src="https://user-images.githubusercontent.com/14843038/44866028-02425f00-ac52-11e8-9059-b84f4a63f1df.png">

```
let routeSummary: [RouteSummaryElement]  = [
    [RouteSummaryElement(stopName: "Millstein  Hall" , direction: .bus(70), shouldStayOnBus: false),
      RouteSummaryElement(stopName: "Collegetown Crossing" , direction: .bus(30), shouldStayOnBus: false),
      RouteSummaryElement(stopName: "Commons - Seneca Street" , direction: nil, shouldStayOnBus: false)
]
```

### Stay on Bus Route
<img width="408" alt="screen shot 2018-08-30 at 12 47 28 pm" src="https://user-images.githubusercontent.com/14843038/44866311-e1c6d480-ac52-11e8-80b1-99733f480ebf.png">

```
let routeSummary: [RouteSummaryElement]  = [
    [RouteSummaryElement(stopName: "Millstein  Hall" , direction: .bus(70), shouldStayOnBus: false),
      RouteSummaryElement(stopName: "Collegetown Crossing" , direction: .bus(30), shouldStayOnBus: true),
      RouteSummaryElement(stopName: "Commons - Seneca Street" , direction: .walk, shouldStayOnBus: false)
      RouteSummaryElement(stopName: "Waffle Frolic", direction: nil, shouldStayOnBus: false)
]
```

### Just Walking Route
<img width="409" alt="screen shot 2018-08-30 at 12 49 52 pm" src="https://user-images.githubusercontent.com/14843038/44866421-336f5f00-ac53-11e8-8d77-3bd1d57995fd.png">

```
let routeSummary: [RouteSummaryElement]  = [
    [RouteSummaryElement(stopName: "Current location" , direction: .walk, shouldStayOnBus: false),
      RouteSummaryElement(stopName: "Commons - Seneca Street", direction: nil, shouldStayOnBus: false)
]
```

### Bus Stop with Walking Route
<img width="410" alt="screen shot 2018-08-30 at 12 53 29 pm" src="https://user-images.githubusercontent.com/14843038/44866617-bf818680-ac53-11e8-9ee9-19ac67d3b2a0.png">

```
let routeSummary: [RouteSummaryElement]  = [
    [RouteSummaryElement(stopName: "Baker Flagpole" , direction: .bus(90), shouldStayOnBus: false),
      RouteSummaryElement(stopName: "Commons - Seneca Street", direction: .walk, shouldStayOnBus: false),
      RouteSummaryElement(stopName: "Waffle Frolic", direction: nil, shouldStayOnBus: false)
]
```

**Comment by mattbarker016** [comment]
@AAAstorga How much progress was made here? Just curious.

**Comment by mattbarker016** [comment]
# Summary
The front end currently modifies our response data before displaying it, but this functionality should be in the backend.

## Implementation / Scope

To be defined by @JunyoungLim.

## Key issue
- We must maintain the V1 API endpoints and all relevant validation tests since not everyone updates their app and we don't want to introduce breaking changes. Therefore, V2 has to use separate but similar endpoints, and we don't want to duplicate files or functionality.
- Implementing tests to work with multiple versions of the API

**Comment by kevinchan159** [comment]
seems like Jared worked on this (https://github.com/cuappdev/ithaca-transit-backend/commit/e5b2903d3b2c45a653bc3c0315a4725296ce54d5). given that the codebase has changed so much though, it might be easier to just rewrite it from scratch, using his work as reference.

**Comment by young-k** [comment]
Was this finished? @kevinchan159 @alanna-zhou 

Even if it's deprecated, we should close it

**Comment by kevinchan159** [comment]
yeah its done
