### ISSUE TITLE
Replace Axios with Request in all routes

### ISSUE THREAD

**Issue by zeladada** [cuappdev/ithaca-transit-backend#46]
Axios fails and causes unhandled promise and undefined variable errors sometimes, especially when running in dev mode, and we don't want that.

Replace all remaining Axios code with Request. The API calls in allStops and some other routes have already been replaced with Request so take a look at those for guidance. Also, Postman will generate Node with Request code so one can also use Postman to verify the request and code works before copying it into the project.

Axios: https://github.com/axios/axios
Request: https://github.com/request/request

**Comment by JunyoungLim** [comment]
Closed with PR #63
