### ISSUE TITLE
[Bug] Depart Direction does not have a route number

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-backend#59]
We're sending a Direction with `"type" : "depart"` but it has `"routeNumber" : null`, which shouldn't occur. Below are the offending logs. We received two emails about the issue, each saying to "Change bus 0 to 93").

Check the logs [here](https://github.com/cuappdev/ithaca-transit-backend/files/2398575/logs.zip) there is one additional set in #transit-email if needed.

Below is a snippet of the error, part of a direction object.

```
...
          "stayOnBusForTransfer": false,
          "routeNumber": null, // should not be null when type == "depart"!
          "type": "depart",
          "endLocation": {
            "lat": 42.453422973754023,
            "long": -76.481498997244955
          },
...
```

**Comment by mattbarker016** [comment]
We got a new email about this issue last night, making it 3 in total. Any progress on this?

**Comment by JunyoungLim** [comment]
Sorry, I just realized that I was assigned to this task. Does it call a function within `RouteRouter.js` if `type == "depart"`? I will try to figure out the reason asap.

**Comment by mattbarker016** [comment]
**Email #4**
<img width="575" alt="image" src="https://user-images.githubusercontent.com/8039928/45984678-29613600-c030-11e8-8e08-af3effbea59b.png">

**Comment by mattbarker016** [comment]
Testing 123

**Comment by zeladada** [comment]
#72 done
