### ISSUE TITLE
Analytics: Replace Register logging

### ISSUE THREAD

**Issue by zeladada** [cuappdev/ithaca-transit-backend#61]
AppDev is creating a new logging/analytics service that can store data in AWS. We are replacing the current error logging system that uses Register and adding analytics support.

**Comment by zeladada** [comment]
Progress made with #92

**Comment by mattbarker016** [comment]
# Summary
Replace Register logging. Use Chronicle to log requests and other data that TCAT can use. Use our own data to provide better route suggestions.

## Specific Goal: Highlight Needed Bus Routes
We want to provide useful information to TCAT to improve their service. With Analytics, we want to figure out what are popular routes that people want to use, but the current bus routes don't serve this need. In other words, we want to identify start and end locations that people are actively searching that current bus routes don't serve well. This last part is subjective, but we can define poor routes as follows:

- High number of transfers (>= 1 transfer)
- Moderate to high amount of walking
     - Hills would add to this, but this may be out of scope with our data
- Low number of routes that aren't close to the requested time

Feel free to think of any more qualifications! 

## Implementation / Scope
- Adding and improving logging utilities
- Improving error handling
- Chronicle integration by either 
    - **Fixing** appdev.js OR 
    - **Copying the files over** and modifying them
- Defining and implementing useful data collection
- A way to visualize the data
- Using the data to improve navigation calculations
