### ISSUE TITLE
Create single install and run method and remove alternative options

### ISSUE THREAD

**Issue by zeladada** [cuappdev/ithaca-transit-backend#75]
We currently have bash scripts, Dockerfiles, and npm scripts in package.json, so there are many ways to setup and run the project. However, none of them result in the exactly same environment setup. Having multiple setup scrips is also resulting in a lot of repeated work and bugs. We should only have one way to setup and run the project to avoid any bugs or differences in behavior that might arise from having multiple possible environment setups, especially in deployment. We should use a combination of the existing scripts to create the behavior we want.

https://medium.com/travis-on-docker/why-and-how-to-use-docker-for-development-a156c1de3b24

**Comment by young-k** [comment]
For this, I think we should just run the node app from terminal, and run `docker-compose up` to start the other three services. As long as it works with @aliciaxw's setup, everything should be good.

**Comment by zeladada** [comment]
I'll take a look when I get the chance to since I don't know what the best solution is. My goal is to be able to automatically setup and run different modes with one command. For example start-dev installs and starts all dependencies and services as needed then runs in development mode with automatic builds and testing. Meanwhile start does a hard reset of all caches and services then runs in production mode. I want to have a Dev mode

**Comment by zeladada** [comment]
Solved with #78
