### ISSUE TITLE
Analytics: Highlight needed bus routes

### ISSUE THREAD

**Issue by mattbarker016** [cuappdev/ithaca-transit-backend#95]
# Goal
We want to provide useful information to TCAT to improve their service. With Analytics, we want to figure out what are popular routes that people want to use, but the current bus routes don't serve this need. In other words, we want to identify start and end locations that people are actively searching that current bus routes don't serve well. This last part is subjective, but we can define poor routes as follows:

- High number of transfers (>= 1 transfer)
- Moderate to high amount of walking
     - Hills would add to this, but this may be out of scope with our data
- Low number of routes that aren't close to the requested time

Feel free to think of any more qualifications! 

## Implementation / Scope
- Adding and improving logging utilities
- Improving error handling
- Chronicle integration by either 
    - **Fixing** appdev.js OR 
    - **Copying the files over** and modifying them
- Defining and implementing useful data collection
- A way to visualize the data
- Using the data to improve navigation calculations

**Comment by young-k** [comment]
@kevinchan159 can we move this to the analytics repo?
